name: Integration Tests

on:
    push:
        paths:
            - gen3-integration-tests/**

jobs:
    run_integration_tests:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: gen3-integration-tests

        env:
          JENKINS_USERNAME: PlanXCyborg
          JENKINS_PASSWORD: ${{ secrets.JENKINS_API_TOKEN }}
          REPO: ${{ github.event.repository.name }}
          BRANCH: ${{ github.ref_name }}
          PR_NUM: ${{ github.event.number }}

        steps:
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry
                poetry install -vv

            - name: Select CI environment
              run: |
                poetry run python -m utils.gen3_ci.select_ci_environment
                echo $NAMESPACE

            - name: Set Gen3 API keys
              run: |
                mkdir -p $HOME/.gen3
                export NS=$(echo "$NAMESPACE" | tr [:lower:] [:upper:] | tr '-' '_')
                echo $NS
                echo ${{ secrets[format('GEN3_API_KEY_{0}_USER1', '$NS')] }} | jq '.' > $HOME/.gen3/$NAMESPACE.json
                ls $HOME/.gen3
                cat $HOME/.gen3/jenkins-brain.json | jq

            - name: Run tests
              run: poetry run pytest --html=report.html --self-contained-html -n auto -m "not wip"

            - name: Release CI environment
              run: |
                poetry run python -m utils.gen3_ci.release_ci_environment
