name: Integration Tests

on:
    push:
        paths:
            - gen3-integration-tests/**

jobs:
    run_integration_tests:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry
                poetry install -vv
            - name: Run tests
              run:
                poetry run pytest --html=report.html --self-contained-html -n auto
