name: Integration Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_integration_tests:
    name: Run integration tests
    uses: uc-cdis/gen3-code-vigil/.github/.github/workflows/integration_tests.yaml@master
